services:
  mydaily:
    container_name: mydaily
    build: .
    ports:
      - "5555:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - mydaily-db:/app/data

volumes:
  mydaily-db:
